# This file is a template, and might need editing before it works on your project.
# Official docker image.
image: maven:3-jdk-10

stages:
  - test
  - build
  - deploy

java:
  stage: test
  script:
    - mvn verify
  artifacts:
    reports:
      junit:
        - target/surefire-reports/TEST-*.xml
        - target/failsafe-reports/TEST-*.xml

build:
  stage: build
  script: "mvn package"
  artifacts:
    paths:
      - target/*.jar
