# This file is a template, and might need editing before it works on your project.
# Official docker image.
image: maven:3-jdk-10

stages:
  - build
  - deploy

build:
  stage: build
  script: "mvn package"
  artifacts:
    paths:
      - target/*.jar
