version: "2"
services:
  authenticationapp:
    build:
      context: .
      dockerfile: Dockerfile
    image: springbootauthenticationapp
    ports:
    - "8888:8888"
    depends_on:
    - mongo
  mongo:
    image: mongo
    ports:
    - "27017:27017"