version: "2"
services:
  authenticationapp:
    container_name: app
    build:
      context: .
      dockerfile: Dockerfile
    image: sbapp
    ports:
    - "8080:8080"
    environment:
      - SPRING_DATA_MONGODB_URL=mongodb://appmongodb:27017/anoush
    depends_on:
    - mongo
  mongo:
    container_name: appmongodb
    image: mongo
    ports:
    - "27017:27017"