version: "2"
services:
  gitlab-runner:
    container_name: gitlabrunner
    image: gitlab/gitlab-runner:latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  gitlab:
    container_name: gitlab
    image: gitlab/gitlab-ce
    user: root
    restart: always
    ports:
      - "8080:80"
      - "8022:22"
    volumes:
      - gitlabconfig:/etc/gitlab
      - gitlablogs:/var/log/gitlab
      - gitlabdata:/var/opt/gitlab
volumes:
  gitlabconfig:
  gitlablogs:
  gitlabdata:
#  gitlab-runner:

#  docker exec -it gitlabrunner gitlab-runner register -n --url http://10.0.0.140:8080/ --registration-token DwxNMrywRzaNWWNd1ay8 --clone-url http://10.0.0.140:8080/ --executor docker --docker-image "docker:latest" --docker-privileged